"""rename address

Revision ID: 01af6a549ed2
Revises: 52448ab592ef
Create Date: 2024-06-27 19:21:02.862514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01af6a549ed2'
down_revision = '52448ab592ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###